<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->basePath(); ?>/lib/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->basePath(); ?>/lib/css/font-awesome.css" />
        <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->basePath(); ?>/src/css/style.css" />
        <?php echo $this->headLink() ?>
		
		<script type = "text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-47459006-1']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script');
				ga.type = 'text/javascript';
				ga.async = true;
				ga.src = ('https:' === document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0];
				s.parentNode.insertBefore(ga, s);
			})();
		</script>
    </head>
    <body>        
		<nav class="navbar navbar-inverse topnav" role="navigation">
			<div class="logo">
				<a href="<?php echo $this->basePath(); ?>/">GAExamples</a>
			</div>
		</nav>
		<div id="hidden-cookies" class="hidden"><pre><?php print_r($_COOKIE); ?></pre></div>
        <?php echo $this->content; ?>
		<script src=<?php echo $this->basePath(); ?>"/lib/js/jquery-2.0.3.js"></script>
		<script src=<?php echo $this->basePath(); ?>"/lib/js/modernizr.js"></script>
        <script src=<?php echo $this->basePath(); ?>"/lib/js/bootstrap.js"></script>
        <?php echo $this->headScript(); ?>
    </body>
</html>
