<div class="row listings">
	<div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
		<form class="form-horizontal" role="form">
			<div class="form-group has-success has-feedback">
				<div class="col-sm-12">
					<input type="text" class="form-control" id="inputSuccess3"  placeholder="Filter. e.g. Page funnel"/>
					<i class="fa fa-info orange"></i> 
				</div>
			</div>
		</form>

		<hr />

		<div class="center">
			<h3>Most Popular</h3>
			<div class="results">65 of 212 results</div>
		</div>

		<div class="row">
			<div class="col-md-4">
				<button type="button" class="btn btn-default  btn-block" data-toggle="collapse" data-target="#1">
					<div class="help-icons outbound-links"></div>

					<h4>Outbound links</h4>
				</button>

				<div id="1" class="collapse desc">
					<h4>Outbound links</h4>
					This example illustrates how to use Google Analytics virtual pageviews to create a funnel that tracks conversion success for a multi-step account creation process. 

					<hr />
					<a href="funnel.html" class="btn btn-default">Open example <i class="fa fa-caret-right"></i></a>  <a href="#" class="btn btn-default" alt="Favorited"><i class="fa fa-star orange"></i></a>
				</div>
			</div>

			<div class="col-md-4">
				<button type="button" class="btn btn-default  btn-block" data-toggle="collapse" data-target="#2">
					<div class="help-icons single-funnel"></div>

					<h4>Single page funnel</h4>
				</button>

				<div id="2" class="collapse desc">
					<h4>Single page funnel</h4>
					This example illustrates how to use Google Analytics virtual pageviews to create a funnel that tracks conversion success for a multi-step account creation process. 

					<hr />
					<a href="/ex/single-page-funnel" class="btn btn-default">Open example <i class="fa fa-caret-right"></i></a>  <a href="#" class="btn btn-default" alt="Favorited"><i class="fa fa-star orange"></i></a>
				</div>
			</div>

			<div class="col-md-4">
				<button type="button" class="btn btn-default  btn-block" data-toggle="collapse" data-target="#3">
					<div class="help-icons outbound-links"></div>

					<h4>Single page funnel</h4>
				</button>

				<div id="3" class="collapse desc">
					<h4>Single page funnel</h4>
					This example illustrates how to use Google Analytics virtual pageviews to create a funnel that tracks conversion success for a multi-step account creation process. 

					<hr />
					<a href="funnel.html" class="btn btn-default">Open example <i class="fa fa-caret-right"></i></a>
				</div>
			</div>

		</div>

		<!-----end row----->

		<div class="row">
			<div class="col-md-4">
				<button type="button" class="btn btn-default  btn-block" data-toggle="collapse" data-target="#1">
					<div class="help-icons outbound-links"></div>
					<h4>Single page funnel</h4>
				</button>
				<div id="1" class="collapse desc">
					<h4>Single page funnel</h4>
					This example illustrates how to use Google Analytics virtual pageviews to create a funnel that tracks conversion success for a multi-step account creation process. 
					<hr />
					<a href="#" class="btn btn-default">Open example <i class="fa fa-caret-right"></i></a>  <a href="#" class="btn btn-default" alt="Favorited"><i class="fa fa-star orange"></i></a>
				</div>
			</div>
			<div class="col-md-4">
				<button type="button" class="btn btn-default  btn-block" data-toggle="collapse" data-target="#2">
					<div class="help-icons outbound-links"></div>
					<h4>Single page funnel</h4>
				</button>
				<div id="2" class="collapse desc">
					<h4>Single page funnel</h4>
					This example illustrates how to use Google Analytics virtual pageviews to create a funnel that tracks conversion success for a multi-step account creation process. 
					<hr />
					<a href="#" class="btn btn-default">Open example <i class="fa fa-caret-right"></i></a>  <a href="#" class="btn btn-default" alt="Favorited"><i class="fa fa-star orange"></i></a>
				</div>
			</div>

			<div class="col-md-4">
				<button type="button" class="btn btn-default  btn-block" data-toggle="collapse" data-target="#3">
					<div class="help-icons outbound-links"></div>
					<h4>Single page funnel</h4>
				</button>

				<div id="3" class="collapse desc">
					<h4>Single page funnel</h4>
					This example illustrates how to use Google Analytics virtual pageviews to create a funnel that tracks conversion success for a multi-step account creation process. 

					<hr />
					<a href="#" class="btn btn-default">Open example <i class="fa fa-caret-right"></i></a>
				</div>
			</div>

		</div>
		<!-----end row----->
		<hr />
		<a href="#" id="load-more-button" class="btn btn-default btn-block">Load more <i class="fa fa-caret-down"></i></a>
	</div>
</div>
